title: Happy Rotter and the Endless Upcoming Books
author: Happy Rotter
description: >-
  I'm Happy Rotter and this is my blog. I can do whatever I want because I am no longer at The-Place-Whose-Name-I-Can't-Remember. That place is miserable, horrible, and no good word can ever be used to describe that place.
baseurl: "/"
# url: "https://infinitynbeyond.me"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

show_excerpts: true # set to false to remove excerpts on the homepage
gems:
  - jekyll-paginate-v2

  # Pagination Settings
pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

permalink: /:year/:month/:title.html

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
